### ISSUE TITLE
Left 'App Looks Like' Pane Update

### ISSUE THREAD

**Issue by mschultz6** [pilrhealth/pilrhealth-issues#219]
“This is what app will look like” (Left pane where we add cards) is not updating when the Order of an Instruction/Welcome Card is changed, even though the reorder is reflected on the iPhone.

**Comment by jaredsieling** [comment]
This is only when reordering the tab content cards on the main builder page, and then clicking "Save order".  Because the left preview app is not ajax, it is not updated.  

I would suggest we have the "Save Order" button just refresh the page, so we don't have to move the preview to ajax, at this point.
