### ISSUE TITLE
Permissions by project: Clicking no to all permissions removes member from project

### ISSUE THREAD

**Issue by mschultz6** [pilrhealth/pilrhealth-issues#231]
Add a member to a project, then, clicking edit and then removing all permissions by clicking them all to "No" removes them from the project.

 (This makes sense but could be an unintended consequence since there is a Trash can Icon that already does this)

In addition, if adding a member without ANY permissions is something that should be able to be done (per previous issue), then clicking No on all permissions for someone who already had permissions shouldn't remove them from project.

**Comment by jaredsieling** [comment]
I agree with possible confusion on this, however, because 'membership' is actually just having one or more permissions on the organization, we cannot allow a member to have no permissions.

I suggest to handle confusion, we simple put a 'NOTE" text at the bottom of the form, informing the user that having no permissions for a user will mean they are not a "member".
