### ISSUE TITLE
500 Error on deleting a project

### ISSUE THREAD

**Issue by welsh11** [pilrhealth/pilrhealth-issues#403]
I have previously deleted a project from my organisation:

https://qa.pilrhealth.com/project/actigraph_test_2/dashboard/index

But it still appears in my list.  When I try and delete it again I get a 500 error page.

I believe I may have previously removed some of the participants from the project. Maybe that cause the issue?

**Comment by tdschenk** [comment]
I was unable to recreate this issue, but it was being thrown because the isDeleted field in the project db was missing for this project. I have changed the migration that checked for this field missing and sets it to false from running once (when project deletion was implemented 3 months ago) to running always upon deployment. This should fix the issue.

**Comment by tdschenk** [comment]
Closed by commit: https://github.com/MeiResearchLtd/s4r-general/commit/553e64f84bfe0c1c46b6d26fc8da23b7aa94a911
