### ISSUE TITLE
Participant Template Assignment

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#433]
Server: qa.pilrhealth.com
Page: /project/nusi_kee_study_phase/participant/show/56956530e4b033a0e96ed53d
User: ewohlers
Project: nusi_kee_study_phase

No schedule set for participant added to template assignment other than default assignment. Epochs were set for TRI template, but they are not displayed on the participant schedule.

**Comment by paul-ferguson** [comment]
I think the confusion comes from the fact that if there is only one Epoch we don't show it on the Participant Schedule page, since it would just show the same information as the Period. I see that Day11 has two Epochs though and that is not displaying correctly.

**Comment by mgm7734** [comment]
Subject: Re: Issue 433
Date: January 19, 2016 at 4:44:34 PM CST
To: Paul Ferguson <paul.ferguson@objectpartners.com>

This was related to the template assignments. I had not assigned them correctly. I talked to Phyllis about it. Sorry the issue didn't get removed. 

Erica 

On Jan 19, 2016, at 4:19 PM, Paul Ferguson <paul.ferguson@objectpartners.com> wrote:

Hello Erica,

I am currently looking at Issue 433, https://github.com/pilrhealth/pilrhealth-issues/issues/433, and have a question for you. Is the issue when your viewing a Participants Schedule with Periods, who are not scheduled yet, your not shown the Epochs for each Period? For example Participant pbrc_ex https://qa.pilrhealth.com/project/nusi_kee_study/participant/show/5670652ae4b0c17035be2aa0. Here is a screen capture of that page too. 

If this is the case it is because we currently don’t show the Epochs until the Period is scheduled. I just want to confirm what the issue is before we figure out the best way to fix it. Thank you.
