### ISSUE TITLE
EMA Versioning not being handled correctly-Mixed EMA Config

### ISSUE THREAD

**Issue by bikerjohn** [pilrhealth/pilrhealth-issues#434]
Mixed EMA Config(s) Version Test Scenario
Created a new EMA Config within an existing project
The new EMA Config uses a new style trigger (requires the v2 api)
Added a device to a user (that had no previous device)
Tried to login with on the Mobile App as the new user
Received a "...not able to find a user with that Login ID and Authentication Code." message
The system showed the user as having connected but the user was never presented with an EMA Config.

**Comment by bikerjohn** [comment]
Retest
Used the Complex Project Setup
Assigned a device to user 2030
Assigned the Sample Survey ema config
Tried to login 
Received the "Sorry, we were not able to find a user with the Login...."

Does not look resolved

**Comment by jmusacchio-gap** [comment]
This issue seemed to be a problem with TriggerFireCountCondition. On Monday I changed the TriggerFireCountCondition to hold the referenced trigger (relation) instead of the trigger code (string). So the ema config had a trigger with the old version that was crashing. Removing the trigger that caused the problem fixed the issue.

**Comment by bikerjohn** [comment]
Reran the test procedure with multiple userid's out to the mobile app.  They all work as expected.  Closing the ticket.
