### ISSUE TITLE
Bulk Participant Load Function

### ISSUE THREAD

**Issue by bikerjohn** [pilrhealth/pilrhealth-issues#437]
Tested the bulk load function.  I ran 2 scenario's
All records correct -- worked correctly -- new users created, ready to be assigned
Added a dup record -- worked correctly (may still be a problem)
  In this case the system correctly found the second record and created an exception, but it loaded all the records including the first instance of the dup'd record.  Not sure if this is an issue, but it more or less assumes the records are identical or the correct record is the first one.  This is an instance of first in wins.  There may be instances where the second record is the correct instance, so in that case this implementation will load the wrong record and reject the second record as a dup.

Also tried some dups across files with some interesting results.  

This is the second source file.  I injected 2 issues.  A dup within this file(participant code 2052), and a dup with a previous file(participant code 2040).  
![source_import_file](https://cloud.githubusercontent.com/assets/11665857/12277709/7b017206-b942-11e5-94e3-87e73a0922ee.PNG)

As you can see the second record for participant 2052 was not loaded.  Note in the test I changed the descriptions between these records, so the dup checking is based on participant code (which I expected).  However, note that participant code 2040 is not identified as a dup.
![bulk_load_exceptions](https://cloud.githubusercontent.com/assets/11665857/12277707/7aff700a-b942-11e5-8b94-16af62d8fcb0.PNG)

Furthermore - participant code 2040 is not showing in the successfully loaded list
![bulk_load_success](https://cloud.githubusercontent.com/assets/11665857/12277706/7afd88f8-b942-11e5-8516-313efb99e4d1.PNG)

Finally, participant code 2040 is no longer showing in the coordinate user page.  Did it get deleted?
![bulk_load_result](https://cloud.githubusercontent.com/assets/11665857/12277708/7afff6f6-b942-11e5-9ca8-5f53113ec007.PNG)

**Comment by jmusacchio-gap** [comment]
Regarding to "participant code 2040 is not showing in the successfully loaded list" is due to the missing header row on the csv file (already described [here](https://github.com/pilrhealth/pilrhealth-issues/issues/440#issuecomment-171295066))
The bulk add doesn't update records, so in your test case the first one is imported due to top-down sequential processing (there is no way to know that the second one is more important). 
What can be done is to update existing database participants, in this case the first one will be created and the second record will update the first one (I guess Phyllis didn't want to update existing participants, just to inform that it already exists).
What we can do is to perform duplicate checking on the file and skip those that appear more than once in the file, avoiding the creation of the participant cause we don't know which one is more important.

**Comment by bikerjohn** [comment]
For an in file dup (two rows with identical values) I am more comfortable with us suspending the process with a message noting where the dups occurred, allowing the user to modify the file, and having them resubmit.  While participant code is a key identifier in the system, it does not map to any real world concept, so in my mind it is not critical to enforce this process now.  Also, it is possible to modify the description field after a user is created, so if it were important that a particular description be attached to a participant code it is possible to achieve that by editing the loaded records after the fact.  I leave it up to the engineering team to decide if they want to tackle the in file dup now.
