### ISSUE TITLE
pilr_health_compliance_navigation_issues

### ISSUE THREAD

**Issue by bikerjohn** [pilrhealth/pilrhealth-issues#518]
The Compliance Link Text shows in multiple screens.  It shows in the EMA Configuration Builder and the PiLR EMA App page.   Also, if you navigate to the compliance report menu, there is no way to return to the screen you arrived from. 

The user (research team) does not create any content for compliance, so it feels inappropriate to have it appear on the EMA Configuration Builder Page.

If we limit the entry to this summary report as coming from the PiLR EMA App page, we should add the Compliance Data page name to the breadcrumbs so the user has a convenient way to return.

**Comment by tdschenk** [comment]
![pilr 0 devuser 0 s sample ema project](https://cloud.githubusercontent.com/assets/5633138/14395534/dc0e4bac-fd97-11e5-90d6-8d2c00bd618e.png)

@bikerjohn Is this acceptable? I added the 4 option navigation header to the Compliance page so now you can easily navigate back from the page you came from. This made the most sense to me since that header is displayed when you access any of the other 3 pages that are available on it. 

In my opinion it is better to leave the Compliance link on the EMA Config Builder page, but I can easily remove that if you still think it is inappropriate to have there.

**Comment by bikerjohn** [comment]
ok with solution on compliance page.  Still want the link removed from the EMA Config Builder page.

**Comment by tdschenk** [comment]
The 4 option navigation header exists on every builder page (creating surveys, triggers, etc.), not just the main config page that you showed me. We could remove the entire header from all of these pages and add breadcrumbs that lead farther backwards, but I don't think it would be worthwhile as it would remove the consistency from the navigation process.

**Comment by bikerjohn** [comment]
ok, I thought that might be the case.  I am ok with leaving that sub-header.


On Mon, Apr 11, 2016 at 1:09 PM, Tyler Schenk <notifications@github.com>
wrote:

> The 4 option navigation header exists on every builder page (creating
> surveys, triggers, etc.), not just the main config page that you showed me.
> We could remove the entire header from all of these pages and add
> breadcrumbs that lead farther backwards, but I don't think it would be
> worthwhile as it would remove the consistency from the navigation process.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pilrhealth/pilrhealth-issues/issues/518#issuecomment-208481690>
>



-- 
John J. Shade
