### ISSUE TITLE
Failed to export project settings, error message

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#628]
Server: qa.pilrhealth.com
Page: /project/calorimetertest0719-3/project/components
User: eruud
Project: calorimeter_test_project

Failed to export the project settings "Failed to export the project components. Unfriendly error message was >>>> null", possibly related to template issues on this project but error does not indicate

**Comment by eruud** [comment]
This is when using the Export button at the top of the page, but the problem is probably the template part of the export since that has the same error (export button under the Setup Information Menu)

![image](https://cloud.githubusercontent.com/assets/19293109/17405376/d4ca5d2e-5a24-11e6-9ebb-51b62223ce81.png)

**Comment by eruud** [comment]
Export tested working now, even on projects with schema errors
