### ISSUE TITLE
Project deletion does not delete project

### ISSUE THREAD

**Issue by pilrhealth-slack** [pilrhealth/pilrhealth-issues#704]
Server: qa.pilrhealth.com
Page: /project/eric_test_project/dashboard/index
User: eruud
Project: eric_test_project

When I delete a project I can still see it on the menu and access all data/participants

**Comment by jmusacchio-gap** [comment]
Couldn't reproduce the "menu" part of the reported issue, when the project is deleted, it disappear from menu. Fixed project navigation issue through url, so when a project is deleted, it is not accessible anymore through url.

**Comment by eruud** [comment]
I have not found out how to reproduce this yet, but on the project eric_test_project, project deletion doesn't do anything and the project is still accessible from the menu. When I delete the project it displays a "success" message but I can still open the project from the menu.
https://qa.pilrhealth.com/project/eric_test_project

**Comment by eruud** [comment]
In eric_test_project, there was a duplicate variable created before the duplicate check was implemented. This was preventing me from creating new variables since PiLR checked all variables before it saved. When I removed the duplicate manually I was able to create variables and delete the project. Since it's no longer possible to save duplicate variables, this is not an issue anymore.
